#!/usr/bin/env bash
# A Bash Script that's transfers a file from the client to a server.

if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"
  
 scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/ 

if [ "$?" -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "Error: File transfer failed."
fi

